version: '3'

services:
  tenant-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenant-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - tenant-network

  # Serviço de desenvolvimento (opcional)
  tenant-frontend-dev:
    image: node:16-alpine
    container_name: tenant-frontend-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - tenant-network

networks:
  tenant-network:
    driver: bridge