name: Deploy Application

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to server
        run: |
          # Usando secrets em vez de variáveis expostas
          echo "Conectando via SSH em ${{ secrets.VM_HOSTS }} como ${{ secrets.SSH_USER }}"
          
          # Conexão SSH usando secrets
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.VM_HOSTS }} '
            cd /path/to/application &&
            git pull &&
            docker compose down &&
            docker compose build &&
            docker compose up -d
          ' 